### PR TITLE
adding airgap links

### PR DESCRIPTION
**Pull request by sadiqevani**
related to https://github.com/aeternity/aepp-token-migration/issues/59

### CODE REVIEW

**Comment by sadiqevani** [comment]
@dadaphl I know, though its good that we have a `http / https` independent, so let say we might by accident put links that are `http` but the app runs in `https` it means it will be insecure. This one infers the protocol based on the app protocol.

**Comment by dadaphl** [comment]
@sadiqevani lets say we have the token migration run on `http` by accident and MEW has an error and doesn't redirect for some reason.

**Comment by dadaphl** [comment]
maybe some people will download the aepp and run it locally

**Comment by dadaphl** [comment]
also this PR does more things than the title claims. It was suppose to add airgap links only. Because it lost focus Im rejecting this PR

**Pull request closed without merging**
